### ISSUE TITLE
Deep link question and infinite loop when trying to display TabNavigator

### ISSUE THREAD

**Issue by afrederick1** [quickbirdstudios/RxCoordinator#28]
A change in c26da8c44a38d4c41192af381afc009c57579024 causes the example app to go into an infinite loop when displaying the TabCoordinator.

Animation+Navigation.swift in
```
public func navigationControllerSupportedInterfaceOrientations(_ navigationController: UINavigationController) -> UIInterfaceOrientationMask
```

before:
```
?? navigationController.visibleViewController?.supportedInterfaceOrientations
```

after:
```
?? navigationController.parent?.supportedInterfaceOrientations
```

Not sure why the parent is called into here, other functions in this file also refer to the `visibleViewController`. You can reproduce the infinite loop by replacing `HomePageCoordinator` with `HomeTabCoordinator` in the AppCoordinator `.home` route handler.

––––––––––––––––––––––––––––

I'm also having some issues with deep linking. The first issue is that I cannot get it to work with a TabCoordinator for some reason, I get the `Could not find appropriate router for...` assertion when including a TabCoordinator route into the `deepLink` call.

Also it seems like the first route passed to the `deepLink` function is not used at all, whereas I would expect that route to be treated like all the others passed in. If you use the following implementation for AppCoordinator you will see what I mean:

```
class AppCoordinator: NavigationCoordinator<AppRoute> {

    init() {
        super.init(initialRoute: nil)
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(3)) {
            self.trigger(.deep)
        }
    }

    var homeRouter: AnyRouter<HomeRoute>!

    override func prepareTransition(for route: AppRoute) -> NavigationTransition {
        switch route {
        case .login:
            var vc = LoginViewController.instantiateFromNib()
            let viewModel = LoginViewModelImpl(coordinator: anyRouter)
            vc.bind(to: viewModel)
            return .push(vc)
        case .home:
            self.homeRouter = HomeTabCoordinator().anyRouter
            let animation = Animation(presentationAnimation: StaticTransitionAnimation.flippingPresentation, dismissalAnimation: nil)
            return .present(homeRouter, animation: animation)
        case .deep:
            return deepLink(.login, AppRoute.home, HomeRoute.news, NewsRoute.newsDetail(MockNewsService().mockNews.first!))
        }
    }
}
```

Notable changes are that the initial route is now nil, so you start the app with an empty view. The `deep` route is triggered 3 seconds later, and you would think that you'd first see `login` but that route is not triggered, instead `home` is the first. This could be intended but is non obvious. I'm trying to integrate this lib with a pretty large and complicated app and I'm pushing the boundaries of what it's capable of and have lots of questions, I'd love to be able to chat with you in realtime if possible. Any plans to set up a Slack channel for this repo?

Thanks,
Andrew

**Comment by pauljohanneskraft** [comment]
Hey Andrew!

We will remove these delegate methods (navigationControllerSupportedInterfaceOrientations, tabbarControllerSupportedInterfaceOrientations, navigationControllerPreferredInterfaceOrientation, tabbarControllerPreferredInterfaceOrientation) from the respective AnimationDelegates for now, since we could not find a valid default implementations that works reliably enough... Do you have an idea of what would be suitable as default implementations? We would like to enable users to override these methods by using the delegate-property in the respective coordinator, which is why we need to override them in the AnimationDelegates.

I will look into the deep-linking issue and report back - if that helps you, you can also create a custom chain of routes by using transitions such as `.multiple(.present(nextCoordinator), .trigger(nextRoute, on: nextCoordinator))`.

**Comment by pauljohanneskraft** [comment]
We removed the delegate methods in the most recent commits on feat/v1, as stated above. 

DeepLinking now triggers the first route as well - Thanks for mentioning!

I can't really find an issue with TabBarCoordinator when using deepLinking - could you give a concrete example there?

**Comment by pauljohanneskraft** [comment]
We created a Slack workspace here: https://join.slack.com/t/xcoordinator/shared_invite/enQtNDg5MjUwNTE3NzgzLWE3NDRiMTJhY2QxMWJlODgxYjY1NTliODFhNDM5NTUxNjc2ZWFiY2QzMThmM2MzMzA1Zjc5NmFmMDJhZDliMGE
Feel free to ask us questions there. We cannot, unfortunately, guarantee real-time communication, but you might be able to post questions in a more organized way. Since it is a public Slack workspace, other users may also assist you there.

**Comment by afrederick1** [comment]
I pulled the latest and the deep link issue is resolved! 

I'm not sure what a good default implementation for the delegate methods would be, maybe just by invoking them on an optional proxy delegate similar to how Animation.swift handles the `UIViewControllerTransitioningDelegate` methods? Speaking of that class, I was going to open a PR that changes each function there to be `open`. Since the class is `open` I subclassed it to easily adopt your Animation class with a preexisting animation we have written, but I did have to modify the file locally to change each function from `public` to `open`. If you're not opposed to that idea I'll make the PR.

I think my TabCoordinator issue was related to the first route on `deepLink` not getting invoked, it seems to be working fine now after the update but I'll keep you posted.

Also I tried that slack invite link but it says it's expired. I do have some more questions about redirection routers, I can bring that convo into the slack workspace when I can get in there, it doesn't seem to be public as I can't sign into the workspace.

Thanks again!

**Comment by pauljohanneskraft** [comment]
I'm sorry about the non-working slack invitation link - The one below should work.

https://join.slack.com/t/xcoordinator/shared_invite/enQtNDg4NDAxNTk1ODQ1LTRhMjY0OTAwNWMyYmQ5ZWI5Mzk3ODU1NGJmMWZlZDY3Y2Q0NTZjOWNkMjgyNmQwYjY4MzZmYTRhN2EzMzczNTM

We would be very interested to hear how and what you would modify in your custom Animation-subclass, so that we could maybe offer a better Animation-class in general. At the moment, we envisioned Animation-objects to only be objects storing different transition animations (presentation and dismissal), which then contain the actual animation code, but we are open to other options as well.
