### ISSUE TITLE
how to enable swipe back gesture in navigation controller 

### ISSUE THREAD

**Issue by xdxavier** [quickbirdstudios/RxCoordinator#30]
Hi there,

I want to use native swipe back gesture and tried an example project looks like not working. How to get back the swipe back gesture?

**Comment by pauljohanneskraft** [comment]
Hey - thanks for using XCoordinator, as well as mentioning this issue!

In case you are always using XCoordinator on the `feat/v1` branch, there will soon be a fix, which is already provided in https://github.com/quickbirdstudios/RxCoordinator/pull/31. In the future, the interactivePopGestureRecognizer on your navigationController can simply be disabled, if not needed, but is otherwise used to pop a viewController.
